name: Tagging

description: Generates a tag based on the branch and SemVer

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        ref: main
    - name: Get latest tag
      run: |
        git describe --tags --abbrev=0
        git checkout ${{ github.head_ref }}
      shell: bash
