name: Build

on:
  workflow_call:
    outputs:
      artifact:
        description: Artifact URL
        value: ${{ jobs.build.outputs.artifact }}
    secrets:
      CONTENTFUL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ vars.GOOGLE_ANALYTICS_TRACKING_ID }}
        run: |
          npm i
          npm run build
      - name: Archive production artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public/
