name: Check commit messages

on:
  workflow_call:

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Verify commit messages
        run: bash scripts/validate-commit-message.sh
