name: Cloudfront deploy

on:
  push:
    branches: [ "main" ]
     
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        run: npm run build
          
      - name: Upload to S3
        run: aws s3 sync $GITHUB_WORKSPACE/public s3://sebsv-free-bucket --delete
        
      - name: Invalidate distribution
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"
  
