name: Pull request preparation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files
        run: ls -la ./.github/workflows
      - name: Print tag.yml content
        run: cat ./.github/workflows/tag.yml
