name: Pull request preparation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/tag
