name: Pull request preparation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Hello world!"
