name: Tagging

on:
  workflow_call:

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Echo
        run: echo "Hello world!"
