name: Tag

on:
  workflow_call:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate tag
        run: git describe --tags --abbrev=0
