name: Tag

on:
  workflow_call:
    outputs:
      tag:
        description: Name of the created tag
        value: ${{ jobs.tag.outputs.tag }}

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "/(feat)(\\(.+\\))?!:/"
          minor_pattern: "/(feat)(\\(.+\\))?:/"
      - name: Tag
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin --tags
